### ISSUE TITLE
Tried it out

### ISSUE THREAD

**Issue by pgatt** [wapiflapi/admiral#1]
Hi there, I hope you don’t mind but I gave your modules a demo and found them really cool. I already used the Audible Bernoulli a lot but yours a lot more interesting. Similarly with watches - it’s a really fun take on a very boring multiple. You should totally release them into the wild.

Also, sorry I had to use issues for what really is a comment, feel free to delete this.

**Comment by wapiflapi** [comment]
Thank you so much :-) This being my first modules I really wasn't confident in releasing them. People giving them a chance and liking them means a lot. I'm working on one more module I'll probably add before releasing the plugin. 

Feel free to open a new issue if you have any comments / suggestions / feature requests. I'm now going to close this one though :-) Thanks again for giving this a shot!
