### ISSUE TITLE
Hi!  I love your modules!

### ISSUE THREAD

**Issue by Zenoth** [wapiflapi/admiral#3]
Hi, I didn't know how to talk to you. So sorry for using this space. I love your modules for VCV rack. Especially Watches and Tables. And I wanted to ask you if you have plans to make more modules of this style for VCV? Personally I am creating a setup in VCV rack to make music in the style of how Steevio composes. And your Switched Multiples and your Sequencer are perfect. Perhaps good additions would be modules based on the A-154 Sequencer Controller, A-155 Analog / Trigger Sequencer or the A-185-2 Precision CV Adder from Doepfer. Although I'm sure you would know better than things to create. Anyway, it would be great new Admiral modules. So thank you very much for your fantastic modules and I hope you make new ones soon! Regards!

**Comment by wapiflapi** [comment]
Hey @Zenoth thank you for reaching out! I'm really sorry I didn't see this earlier. For some reason I didn't have my notifications set-up properly.

I'm going to look at everything you mentioned, I'm don't know anything about real world eurorack so I'm learning as I go. Steevio is definitely an inspiration of mine as well! (mostly indirectly through 
mylarmelodies) so I'm really happy it's working for you!

I don't have much time to work on new modules, but I have some ideas! I just (minutes ago) released an alpha version of a new module (Divisioins) you can check it out at https://github.com/wapiflapi/admiral/releases/tag/v1.1-alpha.1 if you want to install it early before it gets to the official vcv library!

Thanks again for reaching out! I'm going to have to close the issue but don't take that the wrong way! I just keep the open issues for ongoing problems / bugs.

**Comment by wapiflapi** [comment]
Hey @Zenoth you can send me an email at wapiflapi+admiral@gmail.com if you want to talk more! I'm definitely interested into talking to people using my modules to see what would be interesting and maybe work together to find new ones! Your suggestions on Doepfer modules are definitely inspiring!
